blank_issues_enabled: true
contact_links:
  - name: Security vulnerability report
    url: https://github.com/smartbartdev/icloud-photos-sync/security/advisories/new
    about: Please report security issues privately.
